<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251123173344 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE media DROP CONSTRAINT IF EXISTS fk_6a2ca10c4584665a');
        $this->addSql('DROP INDEX IF EXISTS uniq_6a2ca10c4584665a');
        $this->addSql('ALTER TABLE media DROP COLUMN IF EXISTS product_id');
        
        $this->addSql('ALTER TABLE over_account DROP CONSTRAINT IF EXISTS fk_b243e171a76ed395');
        $this->addSql('ALTER TABLE product DROP CONSTRAINT IF EXISTS fk_d34a04ad12469de2');
        
        $this->addSql('DROP TABLE IF EXISTS over_account');
        $this->addSql('DROP TABLE IF EXISTS product');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE over_account (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(255) NOT NULL, avatar VARCHAR(255) DEFAULT NULL, namecard VARCHAR(255) DEFAULT NULL, title VARCHAR(255) NOT NULL, endorsement JSON NOT NULL, competitive JSON NOT NULL, last_updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_b243e171a76ed395 ON over_account (user_id)');
        $this->addSql('CREATE TABLE product (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titlz VARCHAR(255) NOT NULL, content TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, category_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_d34a04ad12469de2 ON product (category_id)');
        $this->addSql('ALTER TABLE over_account ADD CONSTRAINT fk_b243e171a76ed395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT fk_d34a04ad12469de2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE media ADD product_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE media ADD CONSTRAINT fk_6a2ca10c4584665a FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE UNIQUE INDEX uniq_6a2ca10c4584665a ON media (product_id)');
    }
}
